"""
The shared set of player abilities, and the shared discretisation settings.

Everything in this project is parameterised by one number: the standard
deviation of the throw, in millimetres. To keep results comparable across
models, every model is solved at the same set of abilities, defined here once.

The bands are named for the standard of play they correspond to. The mapping
from sigma to a standard is via the 3-dart average the model produces, which is
the number a darts player recognises:

    world class     100+        the very best players in the world
    tour standard   85-95       a PDC tour card holder
    county          70-80       a strong county player
    super league    60-70
    league          45-55       a typical league player
    club            35-45
    pub             25-35       casual

The averages in ``ABILITY_BANDS`` are the model's own, measured at
``BOARD_PIXELS`` with the 3-dart MDP; they are recorded here so the band names
can be sanity-checked without re-solving.
"""

from collections import OrderedDict

import numpy as np

# --------------------------------------------------------------------------
# The shared abilities
# --------------------------------------------------------------------------

#: name -> throwing standard deviation in millimetres
ABILITY_BANDS = OrderedDict([
    ("elite", 6.5),
    ("pro", 8.0),
    ("county", 10.0),
    ("super_league", 13.0),
    ("league", 16.0),
    ("club", 20.0),
    ("pub", 28.0),
])

#: Approximate 3-dart average each band produces, for orientation only.
#: Regenerated by scripts/solve_single_player.py, which writes the measured
#: values into results/manifest.csv.
BAND_AVERAGES = OrderedDict([
    ("elite", 100.1), ("pro", 88.8), ("county", 76.5), ("super_league", 62.2),
    ("league", 51.9), ("club", 42.8), ("pub", 32.3),
])

#: A finer grid for sensitivity work (the practice calculator), where only the
#: cheap single-player model is solved and a dense sweep is affordable.
SIGMA_GRID = np.round(np.arange(5.0, 32.1, 0.5), 1)


# --------------------------------------------------------------------------
# The shared discretisation
# --------------------------------------------------------------------------

#: Board resolution. Validated against exact-geometry Monte Carlo in
#: notebooks/experiments/02: 512 is accurate to ~0.2% of expected score, while
#: 256 is out by up to 4% for accurate players and 128 cannot represent an 8mm
#: scoring bed at all.
BOARD_PIXELS = 512

#: Aiming-grid stride for the single-player models: every 2 pixels = 1.76mm.
POINT_STRIDE_SINGLE = 2

#: Aiming-grid stride for the two-player models. The state space is
#: game_start^2, so the aiming grid is the term to economise on; this is then
#: reduced further to its candidate set, which costs <1e-6 darts.
POINT_STRIDE_TWO = 4

GAME_START = 501


def band_sigma(name):
    """Throwing standard deviation in mm for a named ability band."""
    return ABILITY_BANDS[name]


def nearest_band(sigma_mm):
    """The name of the ability band closest to a given sigma."""
    return min(ABILITY_BANDS, key=lambda k: abs(ABILITY_BANDS[k] - sigma_mm))


def three_dart_average(expected_darts, game_start=GAME_START):
    """Convert expected darts to finish into a 3-dart average."""
    return 3.0 * game_start / expected_darts
